version: '3.8'

services:
  # Servicio de base de datos NoSQL
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    # El puerto se expone para poder depurar con herramientas como NoSQL Workbench
    ports:
      - "8000:8000"
    volumes:
      - dynamodb_data:/home/dynamodblocal/data
    networks:
      - ms-network

  # Servicio de mensajería
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - ms-network

# Definición de los volúmenes
volumes:
  dynamodb_data:
  rabbitmq_data:

# Definición de la red
networks:
  ms-network:
    driver: bridge